teste = input("Digite algo:")
print("O tipo primitivo desse valor e {}".format(type(teste)))
print("So tem espacos? {}".format(teste.isspace()))
print("E um numero? {}".format(teste.isnumeric()))
print("E alfabetico? {}".format(teste.isalpha()))
print("E alfanumerico? {}".format(teste.isalnum()))
print("Esta em maiusculas? {}".format(teste.isupper()))
print("Esta em minusculas? {}".format(teste.islower()))
print("Esta capitalizada? {}".format(teste.istitle()))
